language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="edff7da7-bbde-4fb4-a503-39a7994fd918"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -kirbel74@gmail.com
    on_success: never # default: change
    on_failure: always # default: always